spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://8.138.132.63:3306/user_center'
    username: zzy
    password: 88888888
  # session 失效时间
  session:
    timeout: 86400
server:
  address: 0.0.0.0